[google]
client_id = "378412653431-ua6jtkhpasabjopn76aie8ug3ble4d39.apps.googleusercontent.com"
client_secret = "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"

[mongodb]
uri = "mongodb+srv://kesavankesavan73907_db_user:KESAVANwar3@scheme.dcxk9bo.mongodb.net/?retryWrites=true&w=majority"

[admin]
emails = [
    "kesavankesavan73907@gmail.com",
    "neevan764@gmail.com"
]
passwords = [
    "admin123",
    "super123"
]
EOF